#!$PREFIX/bin/bash
pkg up -y
termux-setup-storage
sleep 5
mkdir /sdcard/htdocs
pkg install apache2 -y
rm $PREFIX/etc/apache2/httpd.conf
mv httpd.conf $PREFIX/etc/apache2/
rm $PREFIX/bin/apachectl
chmod +x apachectl
mv apachectl $PREFIX/bin/
clear
echo "Setup Completed Run apachectl to Start Apache2 Server"
echo "Your Document Root is /sdcard/htdocs"
echo "place your web documents in /sdcard/htdocs"
